apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-names-frontend
  namespace: contoso-names-app
  labels:
    app: contoso-names-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoso-names-frontend
  template:
    metadata:
      labels:
        app: contoso-names-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: contoso-names-frontend
        image: cr2fj2ijfoty7ic.azurecr.io/contoso-names-frontend:cb1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NAME_API_SERVICE_HOST
          value: contoso-names-service
        - name: NAME_API_SERVICE_PORT
          value: "80"