apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-names-frontend
  labels:
    app: contoso-names-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoso-names-frontend
  template:
    metadata:
      labels:
        app: contoso-names-frontend
    spec:
      containers:
      - name: contoso-names-frontend
        image: ghcr.io/sabbour/contoso-names-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NAME_API_SERVICE_HOST
          value: contoso-names-service
        - name: NAME_API_SERVICE_PORT
          value: "80"