apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-names-backend
  labels:
    app: contoso-names-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contoso-names-backend
  template:
    metadata:
      labels:
        app: contoso-names-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: contoso-names-backend
        image: ${SERVICE_BACKEND_IMAGE_NAME} # Will be replaced by CI/CD or the Azure Developer CLI
        imagePullPolicy: Always
        resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 300Mi
        ports:
        - containerPort: 80
        env:
        - name: STORAGE_ACCOUNT_BLOB_ENDPOINT
          valueFrom:
              secretKeyRef:
                name: storageaccount-secret  # Will be populated by the Azure Service Operator
                key: blobEndpoint
                optional: false
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
              secretKeyRef:
                name: storageaccount-secret  # Will be populated by the Azure Service Operator
                key: key1
                optional: false