apiVersion: v1
kind: Service
metadata:
  name: contoso-names-backend
  labels:
    app: contoso-names-backend
spec:
  selector:
    app: contoso-names-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80