apiVersion: v1
kind: Service
metadata:
  name: as
  namespace: namespace-workflow-1692743510796
spec:
  type: LoadBalancer
  selector:
    app: as
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000