apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: ${AZURE_RESOURCE_GROUP}-aso
spec:
  location: ${AZURE_LOCATION}
---
apiVersion: storage.azure.com/v1beta20210401
kind: StorageAccount
metadata:
  name: contosonamesstorage
spec:
  location: ${AZURE_LOCATION}
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: ${AZURE_RESOURCE_GROUP}-aso
  accessTier: Hot
  # Save the keys for the storage account into a Kubernetes secret
  operatorSpec:
    secrets:
      key1:
        name: storageaccount-secret
        key: key1
      key2:
        name: storageaccount-secret
        key: key2
      blobEndpoint:
        name: storageaccount-secret
        key: blobEndpoint