apiVersion: v1
kind: Service
metadata:
  name: contoso-names-frontend
spec:
  selector:
    app: contoso-names-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000